# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-05 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180903_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_card_stripe_id',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
