# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-30 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('level-1', 'level-1'), ('level-2', 'level-2'), ('level-3', 'level-3'), ('level-4', 'level-4'), ('level-5', 'level-5'), ('level-6', 'level-6'), ('level-7', 'level-7'), ('level-8', 'level-8'), ('level-9', 'level-9'), ('level-10', 'level-10'), ('level-11', 'level-11'), ('level-12', 'level-12'), ('level-13', 'level-13'), ('legendary', 'legendary'), ('maxed-out', 'maxed-out'), ('max-level', 'max-level'), ('gold', 'gold'), ('gems', 'gems')], max_length=20)),
            ],
        ),
    ]
