# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-17 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('Booster', 'Booster')], max_length=10)),
                ('commission', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
    ]
