# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-15 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20180815_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='billing_first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='billing_last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
