# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-07 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='email',
            name='to',
            field=models.EmailField(max_length=100),
        ),
    ]
