# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-08 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180905_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestemail',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
