# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-30 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_accesstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
