# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-08 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180908_1219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestEmailManager',
        ),
    ]
