# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-28 17:50
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('usd_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('device', models.CharField(choices=[('A', 'Android'), ('I', 'iOS'), ('B', 'Android Or iOS')], max_length=7)),
                ('sold', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=300)),
                ('img_med', models.ImageField(blank=True, null=True, upload_to=accounts.models.main_image_upload_path)),
                ('img_sml', models.ImageField(blank=True, null=True, upload_to=accounts.models.main_image_upload_path)),
                ('supercell_account_email', models.EmailField(max_length=255)),
                ('supercell_email_password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('name_change', models.BooleanField(default=True)),
                ('king_tower', models.SmallIntegerField()),
                ('gold', models.IntegerField()),
                ('gems', models.IntegerField()),
                ('arena', models.CharField(choices=[('GS', 'Goblin Stadium'), ('BP', 'Bone Pit'), ('BB', 'Barbarian Bowl'), ('PP', "P.E.K.K.A's Playhouse"), ('SV', 'Spell Valley'), ('BW', "Builder's Workshop"), ('RA', 'Royal Arena'), ('FP', 'Frozen Peak'), ('JA', 'Jungle Arena'), ('HM', 'Hog Mountain'), ('EV', 'Electro Valley'), ('LA', 'Legendary Arena'), ('C1', 'Challenger 1'), ('C2', 'Challenger 2'), ('C3', 'Challenger 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('M3', 'Master 3'), ('C', 'Champion'), ('GC', 'Grand Champion'), ('UC', 'Ultimate Champion')], max_length=2)),
                ('trophies', models.SmallIntegerField()),
                ('wins', models.IntegerField()),
                ('three_crown_wins', models.IntegerField()),
                ('highest_trophies', models.IntegerField()),
                ('cards_found', models.SmallIntegerField()),
                ('total_donations', models.IntegerField()),
                ('tournament_matches_played', models.SmallIntegerField()),
                ('tournament_cards_won', models.IntegerField()),
                ('clan_name', models.CharField(max_length=50)),
                ('clan_member_rank', models.CharField(choices=[('M', 'Member'), ('E', 'Elder'), ('C', 'Co-Leader'), ('L', 'Leader')], max_length=2)),
                ('clan_trophies', models.SmallIntegerField()),
                ('clan_war_day_wins', models.SmallIntegerField()),
                ('clan_war_cards_won', models.IntegerField()),
                ('challenge_max_wins', models.SmallIntegerField()),
                ('challenge_cards_won', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=accounts.models.image_upload_path)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('W', 'Witch'), ('SG', 'Spear Goblins'), ('BO', 'Bomber'), ('M', 'Musketeer'), ('TM', 'Three Musketeers'), ('G', 'Giant'), ('SA', 'Skeleton Army'), ('K', 'Knight'), ('A', 'Archers'), ('G', 'Goblins'), ('V', 'Valkyrie'), ('MP', 'Mini P.E.K.K.A'), ('BD', 'Baby Dragon'), ('P', 'Prince'), ('MI', 'Minions'), ('S', 'Skeletons'), ('B', 'Balloon'), ('GS', 'Giant Skeleton'), ('BA', 'Barbarians'), ('MH', 'Minion Horde'), ('HR', 'Hog Rider'), ('PK', 'P.E.K.K.A'), ('L', 'Lava Hound'), ('F', 'Fire Spirits'), ('WI', 'Wizard'), ('RR', 'Royale Recruits'), ('GO', 'Golem'), ('MK', 'Mega Knight'), ('RG', 'Royale Giant'), ('EB', 'Elite Barbarians'), ('SP', 'Sparky'), ('BW', 'Bowler'), ('EX', 'Executioner'), ('CC', 'Cannon Cart'), ('RH', 'Royal Hogs'), ('DP', 'Dark Prince'), ('H', 'Hunter'), ('LU', 'Lumberjack'), ('RA', 'Rascals'), ('ID', 'Inferno Dragon'), ('EW', 'Electro Wizard'), ('NW', 'Night Witch'), ('BR', 'Battle Ram'), ('FM', 'Flying Machine'), ('Z', 'Zappies'), ('MA', 'Magic Archer'), ('SB', 'Skeleton Barrel'), ('MM', 'Mega Minion'), ('GU', 'Guards'), ('GR', 'Royale Ghost'), ('PR', 'Princess'), ('IW', 'Ice Wizard'), ('BN', 'Bandit'), ('MN', 'Miner'), ('GG', 'Goblin Gang'), ('DG', 'Dart Goblin'), ('IG', 'Ice Golem'), ('B', 'Bats'), ('IS', 'Ice Spirit'), ('BH', 'Barbarian Hut'), ('XB', 'X-Bow'), ('EC', 'Elixir Collector'), ('GH', 'Goblin Hut'), ('IT', 'Inferno Tower'), ('MT', 'Mortar'), ('T', 'Tesla'), ('BT', 'Bomb Tower'), ('FU', 'Furnace'), ('C', 'Cannon'), ('TB', 'Tombstone'), ('RE', 'Rage'), ('ZA', 'Zap'), ('AW', 'Arrows'), ('FI', 'Fireball'), ('LI', 'Lightning'), ('RO', 'Rocket'), ('FR', 'Freeze'), ('PO', 'Poison'), ('GY', 'Graveyard'), ('GB', 'Goblin Barrel'), ('TN', 'Tornado'), ('CL', 'Clone'), ('BB', 'Barbarian Barrel'), ('HE', 'Heal'), ('GN', 'Giant Snowball'), ('TL', 'The Log'), ('MR', 'Mirror')], max_length=2)),
                ('level', models.SmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='deck',
            field=models.ManyToManyField(blank=True, to='accounts.DeckCard'),
        ),
    ]
