# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-03 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_img_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='arena',
            field=models.CharField(choices=[('GS', 'Goblin Stadium'), ('BP', 'Bone Pit'), ('BB', 'Barbarian Bowl'), ('PP', 'PEKKAs Playhouse'), ('SV', 'Spell Valley'), ('BW', "Builder's Workshop"), ('RA', 'Royal Arena'), ('FP', 'Frozen Peak'), ('JA', 'Jungle Arena'), ('HM', 'Hog Mountain'), ('EV', 'Electro Valley'), ('LA', 'Legendary Arena'), ('C1', 'Challenger 1'), ('C2', 'Challenger 2'), ('C3', 'Challenger 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('M3', 'Master 3'), ('C', 'Champion'), ('GC', 'Grand Champion'), ('UC', 'Ultimate Champion')], max_length=2),
        ),
    ]
