# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-16 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_arena_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('level', models.SmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='spell_deck',
        ),
        migrations.RemoveField(
            model_name='account',
            name='troop_deck',
        ),
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SpellCard',
        ),
        migrations.DeleteModel(
            name='TroopCard',
        ),
        migrations.AddField(
            model_name='account',
            name='deck',
            field=models.ManyToManyField(blank=True, to='accounts.DeckCard'),
        ),
    ]
