# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-17 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_recommended_decks_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='img_sml',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='account',
            name='img_feature',
        ),
        migrations.RemoveField(
            model_name='account',
            name='img_med',
        ),
    ]
