# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-17 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180917_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='player_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
