# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-16 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='clan_member_rank',
            field=models.CharField(choices=[('M', 'Member'), ('E', 'Elder'), ('C', 'Co-Leader'), ('L', 'Leader')], default='m', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='clan_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deckcard',
            name='name',
            field=models.CharField(choices=[('W', 'Witch'), ('SG', 'Spear Goblins'), ('B', 'Bomber'), ('W', 'Witch'), ('M', 'Musketeer'), ('G', 'Giant'), ('SA', 'Skeleton Army'), ('K', 'Knight'), ('A', 'Archers'), ('G', 'Goblins'), ('V', 'Valkyrie'), ('MP', 'Mini P.E.K.K.A'), ('BD', 'Baby Dragon'), ('P', 'Prince'), ('GB', 'Goblin Barrel'), ('MI', 'Minions'), ('S', 'Skeletons'), ('BA', 'Balloon'), ('GS', 'Giant Skeleton'), ('BA', 'Barbarians'), ('MH', 'Minion Horde'), ('HR', 'Hog Rider'), ('PK', 'P.E.K.K.A'), ('L', 'Lava Hound'), ('F', 'Fire Spirits'), ('WI', 'Wizard')], max_length=2),
        ),
    ]
