# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-16 22:07
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180816_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='account',
            name='device',
            field=models.CharField(choices=[('A', 'Android'), ('I', 'iOS'), ('B', 'Android Or iOS')], max_length=7),
        ),
        migrations.AlterField(
            model_name='deckcard',
            name='name',
            field=models.CharField(choices=[('W', 'Witch'), ('SG', 'Spear Goblins'), ('BO', 'Bomber'), ('M', 'Musketeer'), ('TM', 'Three Musketeers'), ('G', 'Giant'), ('SA', 'Skeleton Army'), ('K', 'Knight'), ('A', 'Archers'), ('G', 'Goblins'), ('V', 'Valkyrie'), ('MP', 'Mini P.E.K.K.A'), ('BD', 'Baby Dragon'), ('P', 'Prince'), ('MI', 'Minions'), ('S', 'Skeletons'), ('B', 'Balloon'), ('GS', 'Giant Skeleton'), ('BA', 'Barbarians'), ('MH', 'Minion Horde'), ('HR', 'Hog Rider'), ('PK', 'P.E.K.K.A'), ('L', 'Lava Hound'), ('F', 'Fire Spirits'), ('WI', 'Wizard'), ('RR', 'Royale Recruits'), ('GO', 'Golem'), ('MK', 'Mega Knight'), ('RG', 'Royale Giant'), ('EB', 'Elite Barbarians'), ('SP', 'Sparky'), ('BW', 'Bowler'), ('EX', 'Executioner'), ('CC', 'Cannon Cart'), ('RH', 'Royal Hogs'), ('DP', 'Dark Prince'), ('H', 'Hunter'), ('LU', 'Lumberjack'), ('RA', 'Rascals'), ('ID', 'Inferno Dragon'), ('EW', 'Electro Wizard'), ('NW', 'Night Witch'), ('BR', 'Battle Ram'), ('FM', 'Flying Machine'), ('Z', 'Zappies'), ('MA', 'Magic Archer'), ('SB', 'Skeleton Barrel'), ('MM', 'Mega Minion'), ('GU', 'Guards'), ('GR', 'Royale Ghost'), ('PR', 'Princess'), ('IW', 'Ice Wizard'), ('BN', 'Bandit'), ('MN', 'Miner'), ('GG', 'Goblin Gang'), ('DG', 'Dart Goblin'), ('IG', 'Ice Golem'), ('B', 'Bats'), ('IS', 'Ice Spirit'), ('BH', 'Barbarian Hut'), ('XB', 'X-Bow'), ('EC', 'Elixir Collector'), ('GH', 'Goblin Hut'), ('IT', 'Inferno Tower'), ('MT', 'Mortar'), ('T', 'Tesla'), ('BT', 'Bomb Tower'), ('FU', 'Furnace'), ('C', 'Cannon'), ('TB', 'Tombstone'), ('RE', 'Rage'), ('ZA', 'Zap'), ('AW', 'Arrows'), ('FI', 'Fireball'), ('LI', 'Lightning'), ('RO', 'Rocket'), ('FR', 'Freeze'), ('PO', 'Poison'), ('GY', 'Graveyard'), ('GB', 'Goblin Barrel'), ('TN', 'Tornado'), ('CL', 'Clone'), ('BB', 'Barbarian Barrel'), ('HE', 'Heal'), ('GN', 'Giant Snowball'), ('TL', 'The Log'), ('MR', 'Mirror')], max_length=2),
        ),
    ]
