# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-17 08:54
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180816_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='img',
        ),
        migrations.AddField(
            model_name='account',
            name='img_med',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.main_image_upload_path),
        ),
        migrations.AddField(
            model_name='account',
            name='img_sml',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.main_image_upload_path),
        ),
    ]
