# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-19 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='title',
            field=models.CharField(max_length=24),
        ),
    ]
