# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-18 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180817_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='adjusted_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
            preserve_default=False,
        ),
    ]
