# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-18 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_adjusted_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='price',
            new_name='usd_price',
        ),
        migrations.RemoveField(
            model_name='account',
            name='adjusted_price',
        ),
    ]
