# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-24 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_account_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='deck',
        ),
        migrations.DeleteModel(
            name='DeckCard',
        ),
    ]
