# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-16 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='default',
        ),
    ]
