# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-03 14:53
from __future__ import unicode_literals

import blogs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('title_img', models.ImageField(upload_to=blogs.models.image_upload_path)),
                ('read_time', models.SmallIntegerField()),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=blogs.models.image_upload_path)),
                ('order', models.SmallIntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Post')),
            ],
        ),
    ]
