# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-03 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Rob Rangal', max_length=25),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='written_the',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='read_time',
            field=models.SmallIntegerField(default=5),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
